version: "3.7"

services:

  web:
    image: nginx:1.21.3-alpine
    volumes:
      - ./web:/usr/share/nginx/html

  listmonk:
    image: listmonk/listmonk:v2.4.0
    environment:
      TZ: Etc/UTC
    depends_on:
      - listmonk_db

  listmonk_db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6