version: "3.7"

services:

  web:
    ports:
      - 8080:80

  listmonk:
    ports:
      - 9000:9000
    networks:
      - listmonk
    command: "./listmonk --static-dir=/listmonk/static"
    environment:
      LISTMONK_app__admin_username: listmonk
      LISTMONK_app__admin_password: listmonk
      LISTMONK_app__email_format: both
    volumes:
      - ./listmonk/config.toml:/listmonk/config.toml
      - ./listmonk/static:/listmonk/static
      - ./listmonk/uploads:/listmonk/uploads

  listmonk_db:
    ports:
      - 5432:5432
    networks:
      - listmonk
    environment:
      POSTGRES_PASSWORD: listmonk
      POSTGRES_USER: listmonk
      POSTGRES_DB: listmonk
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

networks:
  listmonk:

volumes:
  listmonk-data:
