version: "3.7"

services:

  web:
    image: nginx:1.21.3-alpine
    expose:
      - 80
    networks:
      - net
      - default
    volumes:
      - ./web:/usr/share/nginx/html
    working_dir: /home/node/app/
    environment:
      VIRTUAL_HOST: ${DOMAIN_FRONTEND}
      LETSENCRYPT_HOST: ${DOMAIN_FRONTEND}
    restart: always

  listmonk:
    expose:
      - 9000
    networks:
      - listmonk
      - net
    volumes:
      - ./listmonk/config.toml:/listmonk/config.toml
      - ./listmonk/static:/listmonk/static
      - ./listmonk_uploads:/listmonk/uploads
    command: "./listmonk --static-dir=/listmonk/static"
    environment:
      VIRTUAL_HOST: ${DOMAIN_NEWSLETTER}
      LETSENCRYPT_HOST: ${DOMAIN_NEWSLETTER}
      LISTMONK_app__admin_username: ${LISTMONK_USER}
      LISTMONK_app__admin_password: ${LISTMONK_PASS}
      LISTMONK_app__email_format: both
    restart: always

  listmonk_db:
    expose:
      - 5432
    networks:
      - listmonk
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: listmonk
      POSTGRES_USER: listmonk
      POSTGRES_DB: listmonk
    restart: always

  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy:alpine
    volumes:
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - /run/docker.sock:/tmp/docker.sock:ro
    networks: 
      - net
    ports:
      - 80:80
      - 443:443
    restart: always

  # redirect www (http/https) -> non-www (https)
  redirect:
    container_name: redirect
    image: adamkdean/redirect
    networks:
      - net
    environment:
      VIRTUAL_HOST: www.${DOMAIN_FRONTEND}
      LETSENCRYPT_HOST: www.${DOMAIN_FRONTEND}
      REDIRECT_LOCATION: https://${DOMAIN_FRONTEND}
      REDIRECT_STATUS_CODE: 301
      PRESERVE_URL: true
    restart: always
  
  certbot:
    image: nginxproxy/acme-companion
    container_name: certbot
    volumes_from:
      - proxy
    environment:
      NGINX_PROXY_CONTAINER: proxy
      DEFAULT_EMAIL: ${EMAIL_ADMIN}
      # ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory # staging
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  listmonk-data:
  data:
  certs:
  html:
  vhost:
  dhparam:
  acme:

networks:
  listmonk:
  net:
    name: net
    external: true
